name: docs-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build MkDocs (strict)
        run: mkdocs build --strict

      # Link checker SOLO sobre archivos locales (ignora http externos)
      - name: Lychee link checker (offline)
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          # Revisamos todos los HTML generados en ./site
          args: --offline --verbose --no-progress --accept 200,206 "./site"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (Opcional) Publica el sitio construido como artefacto de CI
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
